version: "3.3"

services:
    mysql:
        image: mysql:5.6
        ports:
            - "3306:3306"
        container_name: mysql-camagru
        environment:
            - MYSQL_ROOT_PASSWORD=helloworld
            - MYSQL_DATABASE=db_camagru
            - MYSQL_USER=camagru
            - MYSQL_PASSWORD=password123
#        volumes:
#            - ./mysql:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin-camagru
        ports:
            - "8090:80"
        links:
            - mysql:db
